version: "3"
services:
  app:
    container_name: app
    restart: always
    build: .
    network_mode: "host"
    ports:
      - "3001:3001"
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    network_mode: "host"
    ports:
      - "27017:27017"